export const FILMS = {
  REQUEST_FILMS: 'REQUEST_FILMS',
  REQUEST_FILMS_SUCCESS: 'REQUEST_FILMS_SUCCESS',
  REQUEST_FILMS_FAILED: 'REQUEST_FILMS_FAILED',
}

export const FILTERS = {
  SEARCH_ROW: 'FILTERS_SEARCH_ROW',
  NUMBER_PAGE: 'FILTERS_NUMBER_PAGE'
}