export const FILMS = {
  REQUEST_FILMS: 'REQUEST_FILMS',
  REQUEST_FILMS_SUCCESS: 'REQUEST_FILMS_SUCCESS',
  REQUEST_FILMS_FAILED: 'REQUEST_FILMS_FAILED',
};

export const FILTERS = {
  SEARCH_ROW: 'FILTERS_SEARCH_ROW',
  NUMBER_PAGE: 'FILTERS_NUMBER_PAGE',
  PLOT: 'FILTERS_PLOT',
  TYPE: 'FILTERS_TYPE',
};

export const FILM = {
  REQUEST_FILM: 'REQUEST_FILM',
  REQUEST_FILM_FAILED: 'REQUEST_FILM_FAILED',
  REQUEST_FILM_SUCCESS: 'REQUEST_FILM_SUCCESS',
  CLEAR_FILM_INFO: 'CLEAR_FILM_INFO',
};

export const SYSTEM = {
  LOADING_START: 'SYSTEM_LOADING_START',
  LOADING_FINISHED: 'SYSTEM_LOADING_FINISHED',
};

export const AUTH = {
  SING_IN: 'AUTH_SING_IN',
  SING_OUT: 'AUTH_SING_OUT',
};
